name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t iknock/docker-react -f Dockerfile.dev .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Elastic Beanstalk
        uses: aws-action/elastic-beanstalk-deploy@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: "eu-west-3"
          application-name: "frontend"
          environment-name: "Frontend-env"
          bucket-name: "elasticbeanstalk-eu-west-3-905691979741"
          bucket-path: "frontend"
